<?
$wallet = $config['wallet'];
$walletInput = $simpleInput($wallet, 'wallet');
$pid = $wallet['providerId'];

function providerSelected( $id, $providerId) {
  if ( $id == $providerId ) {
      return "selected = \"selected\"";
  }
  return "";
}

?>
<div id="wallet-settings" data-role="collapsible" data-collapsed="true">
	<h3>
		<?= $i18n->_('Wallet Configuration') ?>
	</h3>
        <div data-role="fieldcontain">
                <label for="WalletProvider">
                        <?= $i18n->_('Selected Wallet Provider')?>
                </label>
		<br/>
                <select
                        name="walletProviderId"
                        id="walletProviderId"
                        data-theme="a"
                        data-native-menu="false"
                >
		    <option value="1" <?= providerSelected(1, $pid)?>>Blockchain Wallet</option>
		    <option value="2" <?= providerSelected(2, $pid)?>>Coinbase Wallet</option>
		    <option value="3" <?= providerSelected(3, $pid)?>>Dummy Wallet</option>
                </select>
        </div>

  <!-- Blockchain -->
  <div id="blockchain-wallet-settings" data-role="collapsible" data-collapsed="true">
	<h3>
		<?= $i18n->_('Blockchain Configuration') ?>
	</h3>
	<? $walletInput($i18n->_('Blockchain ID (GUID)'), 'id') ?>
	<? $walletInput($i18n->_('Blockchain Password'), 'mainPass', 'password') ?>
	<? $walletInput($i18n->_('Secondary Password (optional)'), 'secondPass', 'password') ?>
	<? $walletInput($i18n->_('Sending Bitcoin Address'), 'fromAddress') ?>
  </div><!-- /Blockchain -->

  <!-- Coinbase -->
  <div id="coinbase-wallet-settings" data-role="collapsible" data-collapsed="true">
	<h3>
		<?= $i18n->_('Coinbase Configuration') ?>
	</h3>

                <?= $i18n->_('API key provided <strong>must</strong> have the following permissions on the selected Account in order
		to work with this machine:<br/><br/><strong>balance, transactions, send</strong><br/><br/>')?>

	<? $walletInput($i18n->_('Coinbase Api Key'), 'coinbaseApiKey') ?>
	<? $walletInput($i18n->_('Coinbase Api Secret'), 'coinbaseApiSecret', 'password') ?>
	<? $walletInput($i18n->_('Coinbase Account ID to Vend From'), 'coinbaseAccountId') ?>
	<?
	   # TODO Future enhancement (Repurchase BTC)
	   # $walletInput($i18n->_('Minimum Balance to Maintain via Repurchase (BTC)'), 'coinbaseMaintainBalance');
	   # $walletInput($i18n->_('Payment Method for Repurchase'), 'coinbasePaymentMethodId')
	?>
  </div><!-- /Coinbase -->
</div>
